name: Testing CI
# If you update paths, make sure to update them in e2e-test.yml and no-ci.yml as well
on:
  push:
    paths:
      - '*.md'
  pull_request:
    paths:
      - '*.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test-and-coverage:
    name: With ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: with ci
        run: |
          git ls-files -z "*.md" | xargs -0 wc -l | tail -1 | perl -ne 'm/\s*(\d+)/; exit $1 % 2'
        shell: bash
