name: TESTING CI
# If you update paths, make sure to update them in e2e-test.yml and no-ci.yml as well
on:
    push:
      branches:
        - master
      paths:
        - .github/actions
        - "README.md"
    pull_request:
      paths:
        - .github/actions
        - "README.md"

permissions:
    contents: read
        
concurrency:
    group: ${{ github.workflow_ref }}
    cancel-in-progress: true
        
jobs:
    test-run:
      name: Test run
      runs-on: ubuntu-latest
      steps:
        - name: Run
          run: |
            echo wee
          shell: bash